name: ServerManager
version: 1.0

author: Jolen

main: de.ServerManager.ServerManager

commands:

  chatclear:
  night:
  day:
  cclear:
  rl:
  survival:
  creative:
  spectator:
  times:
  gm:
  midnight:
  noon:
  time:
  smhelp:
  sm: